import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
export function gameContext(){
  const root=fileURLToPath(new URL('..',import.meta.url)),noop=()=>{},store=new Map();
  const el=()=>({style:{setProperty:noop},append:noop,appendChild:noop,remove:noop,addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},getContext:()=>null,setAttribute:noop,dataset:{}});
  const c={console:{log:noop,warn:noop,error:noop,info:noop},performance,setTimeout,clearTimeout,setInterval,clearInterval,URL,TextEncoder,requestAnimationFrame:noop,navigator:{},location:{protocol:'http:',origin:'http://localhost',search:''},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},document:{addEventListener:noop,getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[],createElement:el,body:el(),documentElement:el(),fonts:null},Image:class{set src(v){}},addEventListener:noop};
  c.window=c;vm.createContext(c);
  for(const m of readFileSync(join(root,'index.html'),'utf8').matchAll(/<script src="(js\/[^"]+)"><\/script>/g))vm.runInContext(readFileSync(join(root,m[1]),'utf8'),c,{filename:m[1]});
  return vm.runInContext('({BrainArt,BrainGames,BrainSpotTask,BrainPairTask,BrainMathTask,BRAIN_TASKS,BrainTask,BrainTown,SHOP_GAMES,KoboArt,KoboGames,KoboSlideTask,KoboShapeTask,KoboLogicTask,KOBO_TASKS,KoboTask,KoboTown,KadenItems,KadenLive,KadenHallArt,KadenHall,KadenStickerArt,KadenStickers,KeibaRules,KeibaRace,KeibaArt,KeibaUI,KeibaScene,KeibaCorner,MallGuide,IchibanKuji,KujiArt,KujiUI,NeriShops,StickerBook,StickerArt,PetWalk,CHAR_SIZE,HandItems,SLOT_ORDER,HomeToilet,HomeDoors,HomeLife,GowagaWish,VenueScene,VenueHalls,Smaho,Gacha,GachaForest,GachaForestMore,GachaCornerMore,MeeRotation,GachaForestArt,Purikura,SCENES,UI,MAP_DEFS,BAG_INDEX,WorkExp,HeadPair,WEAR_SLOT_KEYS,DinoMuseum,DinoHallArt,Fossils,Museum,FurnTray,WearStock,Loot,PokaDebug,MuseumWear,BurgerMenu,FoodBalance,FashionShow,FashionArt,FashionHall,FashionScene,CHARA_DATA,Care,FOSSIL_DATA,HomeGarden,ParentWardrobe,ParentCare,RoomPresets,HomeRooms,IndoorWalk,NpcLife,WorldScene,Walker,Game,G,NpcArt,TownDialogue,TOWN_DIALOGUE_DATA,TownQuiz,TOWN_QUIZ_DATA,QuizPrizes,TownFolk,TALKS,U,UI,Chara,BAG_INDEX,ITEM_INDEX,localStorage,VenueHalls,VenueHallArt,NerikasuNeighborhood,MacKitchenRound,MacKitchen,SaveBackup,HeiwadaiLife,HeiwadaiArt,HEIWADAI_LAYOUT_DATA,MAP_DEFS,WorldMap,TownRenewal,TownRenewalArt,Save,Transit,WorldArt,Art,BattleElements,SKILLS,ENEMIES,Stats,Sound,SONGS,ModernMusic,NakayoshiPuzzle,PuzzleArcade,PUZZLE_PRIZES,FURN_INDEX,BUY_SHOPS,HomeDesign,MG_TASKS,SHOPS,SCENES,CranePhys,CraneMachines,CraneArt,CraneScene,CraneCam,PrizeArcade,MamaSchedule,FOODS,IkebukuroCatalog,IkebukuroDistrict,IkebukuroVenues,IkebukuroTown,RANGE_DATA,NerikasuTown,NerikasuLayout,Fishing,FISHING_DATA,ItemDex,ItemDexSources,FURNITURE,WEAR_ITEMS,IsoVenue,IsoVenueScene,MallArt,IkeMall,MallGuide,IkeAquarium,AquaArt,IkeWear,WearMannequin,MallMusic,SvgCache,PROFILE,WEAR,MUSEUM_DATA,TOWNSFOLK_DATA,ArcadePrizes,SnackArt,BridgePrizes,IkebukuroItemArt,ArcadeArt,IkeArcade,ShopUI,KorokoroWorld,KOROKORO_TIERS,KOROKORO_RULES,KOROKORO_ORDERS,KOROKORO_BONUS,KorokoroArt,KorokoroBoard,KorokoroTask,KorokoroTown,KOROKORO_SCORE,KOROKORO_SCORE_HOWTO,KOROKORO_SCORE_TEAM,KOROKORO_FACE,KorokoroScore,KorokoroScoreScene,KOROKORO_PRIZES,KorokoroPrizes,FurnLive,FurnModels,FURN_ART,STORE_INTERIORS,StoreArt,SIGN_ICON,HOWTO,SHOP_OWNERS,GameEconomy,MusicDiscs,ShopRewards,ShopRewardArt,RugLamp,FurnCollection,SlowLifePrices,DayTint,TaskBase,ShopScene,ShopDayCap,FossilSell,DinoAward,NeriQuests,AREAS,HomeFloors,HouseScene,ROOM,Seasonal,AnnualFestivals,Farm,FarmArt,FARM_CROPS,FARM_RULES,FarmScene,WorldScenery,Weather,FOOD_ART,FarmCook,FARM_RECIPES,Purikura,PurikuraArt,PurikuraScene,Smaho,Gacha,AquaGifts,FigureStand,Room,GachaArt,MeeRentalWear,MeeFitting,DressUp,SLOT_NAMES,AtlasArt,WorldAtlas,AreaMap,AreaMapArt,ArcadeJpop,ARCADE_JPOP_DATA,CollabGoods,PuzzleCollab,KorokoroCollab,FurnLive,PuriPose,CHARA_GESTURES,CHARA_FACE_EXTRA,charaArmEnds})',c);
}
