// 英語ゲームの 単語（あたまの たいそう・大人むけ・UI-82。オーナーの 依頼 2026-10-04「脳トレは、英語ゲーム（英語は中学生レベルと高校レベル選べる。
// また、英単語の日本語の意味を選択するゲームと、文章中に英語を当てはめるゲームがある。）」）。
// [英語, 品詞, 意味, 似た 意味の なかま（なくて よい）]。品詞: n 名詞・v 動詞・a 形容詞・d 副詞。
// 意味は おなじ レベル・品詞の なかで かさならない。なかまが おなじ 語は まちがいの 選択肢に いっしょに ださない（tools/check-english.mjs）。
// jh 中学: 学習指導要領で 中学までに ならう 語（小学校 600〜700語・中学 1600〜1800語）から。hs 高校: 高校で ふえる 1800〜2500語 から。
// toeic: TOEIC® L&R 対策の ビジネスの 語（下の toeic の コメント）。TOEIC® is a registered trademark of ETS. This product is not endorsed or approved by ETS.
// この ゲームの ために えらんで 意味を つけた もの（単語帳の 写しでは ない）。
const ENG_WORDS = {
  jh: [
    // 名詞
    ["weather", "n", "天気"], ["village", "n", "村"], ["language", "n", "言語"], ["island", "n", "島"], ["forest", "n", "森"],
    ["library", "n", "図書館"], ["museum", "n", "博物館"], ["hospital", "n", "病院"], ["airport", "n", "空港"], ["station", "n", "駅"],
    ["dictionary", "n", "辞書"], ["information", "n", "情報"], ["experience", "n", "経験"], ["future", "n", "未来"], ["history", "n", "歴史"],
    ["culture", "n", "文化"], ["environment", "n", "環境"], ["problem", "n", "問題"], ["reason", "n", "理由"], ["example", "n", "例"],
    ["idea", "n", "考え"], ["memory", "n", "記憶"], ["tradition", "n", "伝統"], ["festival", "n", "祭り"], ["holiday", "n", "休日", "rest"],
    ["vacation", "n", "休暇", "rest"], ["trip", "n", "旅行", "trip"], ["journey", "n", "旅", "trip"], ["tourist", "n", "観光客"], ["passenger", "n", "乗客"],
    ["customer", "n", "顧客"], ["neighbor", "n", "隣人"], ["government", "n", "政府"], ["society", "n", "社会"], ["science", "n", "科学"],
    ["nature", "n", "自然"], ["earth", "n", "地球"], ["planet", "n", "惑星"], ["universe", "n", "宇宙"], ["ocean", "n", "大洋"],
    ["desert", "n", "砂漠"], ["temperature", "n", "温度"], ["season", "n", "季節"], ["century", "n", "世紀"], ["moment", "n", "瞬間"],
    ["vegetable", "n", "野菜"], ["meal", "n", "食事"], ["price", "n", "値段"], ["clothes", "n", "衣服"], ["uniform", "n", "制服"],
    ["tool", "n", "道具"], ["machine", "n", "機械"], ["scientist", "n", "科学者"], ["artist", "n", "芸術家"], ["member", "n", "一員"],
    ["leader", "n", "指導者"], ["citizen", "n", "市民"], ["population", "n", "人口"], ["friendship", "n", "友情"], ["peace", "n", "平和"],
    ["hobby", "n", "趣味"], ["chance", "n", "機会"], ["purpose", "n", "目的"], ["result", "n", "結果"], ["effort", "n", "努力"],
    ["ability", "n", "能力"], ["advice", "n", "助言"], ["question", "n", "質問"], ["letter", "n", "手紙"], ["interview", "n", "面接"],
    ["speech", "n", "演説"], ["conversation", "n", "会話"], ["topic", "n", "話題", "topic"], ["subject", "n", "教科", "topic"], ["report", "n", "報告"],
    ["event", "n", "出来事"], ["accident", "n", "事故"], ["danger", "n", "危険"], ["safety", "n", "安全"], ["health", "n", "健康"],
    ["fever", "n", "熱"], ["medicine", "n", "薬"], ["secret", "n", "秘密"], ["surprise", "n", "驚き"], ["fact", "n", "事実", "true"],
    ["truth", "n", "真実", "true"], ["mistake", "n", "間違い"], ["rule", "n", "規則"], ["law", "n", "法律"], ["area", "n", "地域"],
    ["capital", "n", "首都"], ["street", "n", "通り"], ["bridge", "n", "橋"], ["building", "n", "建物"], ["roof", "n", "屋根"],
    ["wall", "n", "壁"], ["garden", "n", "庭"], ["ground", "n", "地面"], ["cloud", "n", "雲"], ["wind", "n", "風"],
    ["sound", "n", "音"], ["voice", "n", "声"], ["noise", "n", "騒音"], ["kitchen", "n", "台所"], ["office", "n", "事務所"],
    ["company", "n", "会社"], ["factory", "n", "工場"], ["farm", "n", "農場"], ["bottle", "n", "びん"], ["umbrella", "n", "傘"],
    // 動詞
    ["borrow", "v", "借りる"], ["lend", "v", "貸す"], ["forget", "v", "忘れる"], ["remember", "v", "覚えている"], ["decide", "v", "決める"],
    ["choose", "v", "選ぶ"], ["arrive", "v", "到着する", "arrive"], ["leave", "v", "去る"], ["return", "v", "戻る"], ["visit", "v", "訪れる"],
    ["travel", "v", "旅行する"], ["invite", "v", "招待する"], ["introduce", "v", "紹介する"], ["explain", "v", "説明する"], ["understand", "v", "理解する"],
    ["believe", "v", "信じる"], ["hope", "v", "望む", "wish"], ["wish", "v", "願う", "wish"], ["worry", "v", "心配する"], ["agree", "v", "賛成する"],
    ["carry", "v", "運ぶ"], ["catch", "v", "捕まえる"], ["throw", "v", "投げる"], ["break", "v", "壊す"], ["build", "v", "建てる"],
    ["grow", "v", "成長する"], ["protect", "v", "守る"], ["save", "v", "救う"], ["spend", "v", "（時間を）過ごす"], ["waste", "v", "無駄にする"],
    ["collect", "v", "集める"], ["share", "v", "共有する"], ["join", "v", "参加する"], ["practice", "v", "練習する"], ["prepare", "v", "準備する"],
    ["wash", "v", "洗う"], ["order", "v", "注文する"], ["pay", "v", "支払う"], ["sell", "v", "売る"], ["win", "v", "勝つ"],
    ["lose", "v", "失う"], ["fail", "v", "失敗する"], ["succeed", "v", "成功する"], ["finish", "v", "終える"], ["continue", "v", "続ける"],
    ["change", "v", "変える"], ["push", "v", "押す"], ["pull", "v", "引く"], ["touch", "v", "触れる"], ["feel", "v", "感じる"],
    ["shout", "v", "叫ぶ", "shout"], ["laugh", "v", "笑う", "smile"], ["smile", "v", "ほほえむ", "smile"], ["cry", "v", "泣く", "shout"], ["wake", "v", "目を覚ます"],
    ["climb", "v", "登る"], ["fall", "v", "落ちる"], ["hurry", "v", "急ぐ"], ["wait", "v", "待つ"], ["happen", "v", "起こる"],
    ["marry", "v", "結婚する"], ["welcome", "v", "歓迎する"], ["enjoy", "v", "楽しむ"], ["check", "v", "確かめる"], ["count", "v", "数える"],
    ["follow", "v", "ついていく"], ["guess", "v", "推測する", "guess"], ["imagine", "v", "想像する", "guess"], ["notice", "v", "気づく"], ["mean", "v", "意味する"],
    ["solve", "v", "解決する"], ["support", "v", "支える"], ["learn", "v", "学ぶ"], ["wear", "v", "身につけている"], ["draw", "v", "（線で）描く"],
    ["reach", "v", "届く", "arrive"], ["send", "v", "送る"], ["receive", "v", "受け取る"], ["hide", "v", "隠す"], ["repeat", "v", "繰り返す"],
    // 形容詞
    ["important", "a", "重要な"], ["expensive", "a", "高価な"], ["cheap", "a", "安い"], ["difficult", "a", "難しい"], ["famous", "a", "有名な"],
    ["popular", "a", "人気のある"], ["similar", "a", "似ている"], ["different", "a", "異なる"], ["dangerous", "a", "危険な"], ["safe", "a", "安全な"],
    ["delicious", "a", "とてもおいしい"], ["hungry", "a", "空腹の"], ["thirsty", "a", "のどがかわいた"], ["tired", "a", "疲れた"], ["busy", "a", "忙しい"],
    ["free", "a", "暇な"], ["quiet", "a", "静かな"], ["noisy", "a", "うるさい"], ["clean", "a", "清潔な"], ["dirty", "a", "汚い"],
    ["bright", "a", "明るい"], ["dark", "a", "暗い"], ["heavy", "a", "重い"], ["light", "a", "軽い"], ["strong", "a", "強い"],
    ["weak", "a", "弱い"], ["kind", "a", "親切な"], ["polite", "a", "礼儀正しい"], ["honest", "a", "正直な"], ["brave", "a", "勇敢な"],
    ["careful", "a", "注意深い"], ["strange", "a", "奇妙な"], ["wonderful", "a", "すばらしい"], ["terrible", "a", "ひどい"], ["useful", "a", "役に立つ"],
    ["necessary", "a", "必要な"], ["possible", "a", "可能な"], ["natural", "a", "自然の"], ["international", "a", "国際的な"], ["traditional", "a", "伝統的な"],
    ["foreign", "a", "外国の"], ["local", "a", "地元の"], ["huge", "a", "巨大な"], ["empty", "a", "空っぽの"], ["full", "a", "いっぱいの"],
    ["wet", "a", "ぬれた"], ["dry", "a", "乾いた"], ["sick", "a", "病気の"], ["healthy", "a", "健康な"], ["afraid", "a", "こわがって"],
    ["glad", "a", "うれしい"], ["sad", "a", "悲しい"], ["lonely", "a", "さびしい"], ["excited", "a", "わくわくした"], ["surprised", "a", "驚いた"],
    ["angry", "a", "怒った"], ["proud", "a", "誇りに思って"], ["sure", "a", "確かな"], ["main", "a", "主な"], ["wide", "a", "幅の広い"],
    // 副詞
    ["already", "d", "すでに"], ["still", "d", "今でも"], ["soon", "d", "まもなく"], ["again", "d", "再び"], ["often", "d", "しばしば"],
    ["usually", "d", "ふだんは"], ["sometimes", "d", "ときどき"], ["always", "d", "いつも"], ["never", "d", "一度も〜ない"], ["together", "d", "いっしょに"],
    ["quickly", "d", "すばやく"], ["slowly", "d", "ゆっくりと"], ["carefully", "d", "注意深く"], ["suddenly", "d", "突然"], ["finally", "d", "ついに"],
    ["abroad", "d", "海外に"], ["almost", "d", "ほとんど"], ["especially", "d", "特に"], ["probably", "d", "たぶん"], ["recently", "d", "最近"],
    ["early", "d", "早く"], ["easily", "d", "簡単に"], ["actually", "d", "実際に"], ["anywhere", "d", "どこでも"], ["once", "d", "一度"],
  ],
  hs: [
    // 名詞
    ["consequence", "n", "（悪い）結果"], ["evidence", "n", "証拠"], ["opportunity", "n", "好機"], ["advantage", "n", "利点", "benefit"], ["benefit", "n", "恩恵", "benefit"],
    ["burden", "n", "負担"], ["conflict", "n", "対立"], ["crisis", "n", "危機", "crisis"], ["disaster", "n", "災害"], ["emergency", "n", "緊急事態", "crisis"],
    ["phenomenon", "n", "現象"], ["hypothesis", "n", "仮説"], ["theory", "n", "理論"], ["principle", "n", "原理"], ["concept", "n", "概念"],
    ["context", "n", "文脈"], ["attitude", "n", "態度", "attitude"], ["behavior", "n", "ふるまい", "attitude"], ["belief", "n", "信念"], ["custom", "n", "慣習"],
    ["heritage", "n", "遺産"], ["ancestor", "n", "祖先"], ["descendant", "n", "子孫"], ["generation", "n", "世代"], ["poverty", "n", "貧困"],
    ["wealth", "n", "富"], ["income", "n", "収入"], ["expense", "n", "費用"], ["debt", "n", "借金"], ["profit", "n", "利益", "benefit"],
    ["economy", "n", "経済"], ["industry", "n", "産業"], ["agriculture", "n", "農業"], ["resource", "n", "資源"], ["fuel", "n", "燃料"],
    ["pollution", "n", "汚染"], ["climate", "n", "気候"], ["species", "n", "（生物の）種"], ["evolution", "n", "進化"], ["gene", "n", "遺伝子"],
    ["disease", "n", "病気"], ["symptom", "n", "症状"], ["treatment", "n", "治療"], ["surgery", "n", "手術"], ["patient", "n", "患者"],
    ["nutrition", "n", "栄養"], ["emotion", "n", "感情"], ["anxiety", "n", "不安"], ["curiosity", "n", "好奇心"], ["confidence", "n", "自信"],
    ["courage", "n", "勇気"], ["patience", "n", "忍耐"], ["sympathy", "n", "同情"], ["gratitude", "n", "感謝"], ["shame", "n", "恥"],
    ["reputation", "n", "評判"], ["authority", "n", "権威"], ["democracy", "n", "民主主義"], ["election", "n", "選挙"], ["policy", "n", "政策"],
    ["regulation", "n", "規制"], ["treaty", "n", "条約"], ["negotiation", "n", "交渉"], ["obligation", "n", "義務"], ["privilege", "n", "特権"],
    ["welfare", "n", "福祉"], ["architecture", "n", "建築"], ["literature", "n", "文学"], ["philosophy", "n", "哲学"], ["psychology", "n", "心理学"],
    ["statistics", "n", "統計"], ["survey", "n", "調査"], ["experiment", "n", "実験"], ["analysis", "n", "分析"], ["device", "n", "装置", "device"],
    ["equipment", "n", "設備", "device"], ["facility", "n", "施設"], ["vehicle", "n", "乗り物"], ["territory", "n", "領土"], ["boundary", "n", "境界"],
    ["landscape", "n", "風景"], ["horizon", "n", "地平線"], ["atmosphere", "n", "大気"], ["surface", "n", "表面"], ["quantity", "n", "量"],
    ["quality", "n", "質"], ["majority", "n", "大多数"], ["minority", "n", "少数派"], ["proportion", "n", "割合"], ["range", "n", "範囲"],
    ["tendency", "n", "傾向"], ["destination", "n", "目的地"], ["departure", "n", "出発"], ["deadline", "n", "締め切り"], ["priority", "n", "優先事項"],
    ["intuition", "n", "直感", "insight"], ["illusion", "n", "錯覚"], ["prejudice", "n", "偏見"], ["discrimination", "n", "差別"], ["tolerance", "n", "寛容"],
    ["diversity", "n", "多様性"], ["harmony", "n", "調和"], ["isolation", "n", "孤立"], ["cooperation", "n", "協力"], ["competition", "n", "競争"],
    ["achievement", "n", "業績"], ["ingredient", "n", "材料"], ["insight", "n", "洞察", "insight"], ["merchant", "n", "商人"], ["neighborhood", "n", "近所"],
    // 動詞
    ["abandon", "v", "放棄する"], ["acquire", "v", "習得する", "get"], ["adapt", "v", "適応する"], ["adopt", "v", "採用する"], ["admire", "v", "称賛する"],
    ["admit", "v", "認める", "admit"], ["afford", "v", "余裕がある"], ["analyze", "v", "分析する"], ["appreciate", "v", "ありがたく思う"], ["approve", "v", "承認する"],
    ["assume", "v", "仮定する"], ["attach", "v", "取り付ける"], ["attempt", "v", "試みる"], ["attract", "v", "引きつける"], ["avoid", "v", "避ける"],
    ["behave", "v", "ふるまう"], ["bother", "v", "悩ませる", "bother"], ["calculate", "v", "計算する"], ["claim", "v", "主張する", "insist"], ["combine", "v", "組み合わせる"],
    ["compare", "v", "比較する"], ["compete", "v", "競う"], ["complain", "v", "不平を言う"], ["conclude", "v", "結論づける"], ["conduct", "v", "行う"],
    ["confess", "v", "告白する"], ["confirm", "v", "確認する"], ["confuse", "v", "混乱させる"], ["consider", "v", "よく考える"], ["consume", "v", "消費する"],
    ["contain", "v", "含む", "contain"], ["contribute", "v", "貢献する"], ["convince", "v", "納得させる", "persuade"], ["criticize", "v", "批判する"], ["declare", "v", "宣言する"],
    ["decline", "v", "断る", "refuse"], ["define", "v", "定義する"], ["delay", "v", "遅らせる"], ["deny", "v", "否定する"], ["depend", "v", "頼る", "depend"],
    ["deserve", "v", "値する"], ["determine", "v", "決定する"], ["devote", "v", "ささげる"], ["distinguish", "v", "区別する"], ["disturb", "v", "邪魔する", "bother"],
    ["eliminate", "v", "取り除く", "remove"], ["emerge", "v", "現れる"], ["emphasize", "v", "強調する"], ["encourage", "v", "励ます", "encourage"], ["endure", "v", "耐える", "endure"],
    ["establish", "v", "設立する"], ["estimate", "v", "見積もる", "evaluate"], ["evaluate", "v", "評価する", "evaluate"], ["exaggerate", "v", "誇張する"], ["exclude", "v", "除外する", "remove"],
    ["expand", "v", "拡大する", "expand"], ["explore", "v", "探検する"], ["expose", "v", "さらす"], ["extend", "v", "延長する", "expand"], ["forbid", "v", "禁じる", "forbid"],
    ["hesitate", "v", "ためらう"], ["ignore", "v", "無視する", "ignore"], ["imitate", "v", "まねる"], ["imply", "v", "ほのめかす", "imply"], ["impose", "v", "課す"],
    ["improve", "v", "改善する"], ["indicate", "v", "示す", "imply"], ["inform", "v", "知らせる"], ["inherit", "v", "受け継ぐ"], ["insist", "v", "言い張る", "insist"],
    ["inspire", "v", "奮い立たせる", "encourage"], ["interpret", "v", "解釈する", "translate"], ["investigate", "v", "調査する"], ["involve", "v", "巻き込む", "contain"], ["maintain", "v", "維持する"],
    ["manage", "v", "管理する"], ["mention", "v", "言及する", "mention"], ["modify", "v", "修正する"], ["neglect", "v", "怠る", "ignore"], ["obey", "v", "従う"],
    ["observe", "v", "観察する"], ["obtain", "v", "得る", "get"], ["occupy", "v", "占める"], ["oppose", "v", "反対する", "oppose"], ["overcome", "v", "克服する"],
    ["participate", "v", "参加する"], ["persuade", "v", "説得する", "persuade"], ["possess", "v", "所有する"], ["predict", "v", "予測する"], ["prefer", "v", "〜のほうを好む"],
    ["preserve", "v", "保存する"], ["pretend", "v", "ふりをする"], ["prevent", "v", "防ぐ"], ["prohibit", "v", "禁止する", "forbid"], ["promote", "v", "促進する"],
    ["propose", "v", "提案する", "suggest"], ["prove", "v", "証明する"], ["publish", "v", "出版する"], ["pursue", "v", "追求する", "seek"], ["recognize", "v", "認識する", "admit"],
    ["recommend", "v", "勧める", "suggest"], ["recover", "v", "回復する", "restore"], ["reduce", "v", "減らす"], ["refer", "v", "参照する", "mention"], ["reflect", "v", "反映する"],
    ["refuse", "v", "拒む", "refuse"], ["regret", "v", "後悔する"], ["reject", "v", "拒絶する", "refuse"], ["release", "v", "解放する"], ["rely", "v", "当てにする", "depend"],
    ["remain", "v", "残る", "remain"], ["remove", "v", "取り去る", "remove"], ["replace", "v", "取り替える"], ["represent", "v", "代表する"], ["require", "v", "必要とする"],
    ["rescue", "v", "救助する"], ["resemble", "v", "似ている"], ["resist", "v", "抵抗する", "oppose"], ["respond", "v", "応答する"], ["restore", "v", "修復する", "restore"],
    ["reveal", "v", "明らかにする"], ["satisfy", "v", "満足させる"], ["seek", "v", "探し求める", "seek"], ["select", "v", "選び出す"], ["suffer", "v", "苦しむ"],
    ["supply", "v", "供給する"], ["surround", "v", "囲む"], ["survive", "v", "生き残る", "remain"], ["suspect", "v", "疑う"],
    ["tolerate", "v", "我慢する", "endure"], ["transform", "v", "変形させる"], ["translate", "v", "翻訳する", "translate"], ["violate", "v", "違反する"], ["withdraw", "v", "撤退する"],
    // 形容詞
    ["abstract", "a", "抽象的な"], ["concrete", "a", "具体的な"], ["accurate", "a", "正確な", "exact"], ["adequate", "a", "十分な", "enough"], ["ancient", "a", "古代の"],
    ["obvious", "a", "明白な"], ["anxious", "a", "心配して"], ["appropriate", "a", "適切な"], ["available", "a", "利用できる"], ["aware", "a", "気づいて", "aware"],
    ["capable", "a", "能力がある"], ["complex", "a", "複雑な"], ["conscious", "a", "意識している", "aware"], ["considerable", "a", "かなりの"], ["constant", "a", "絶え間ない"],
    ["contemporary", "a", "現代の"], ["crucial", "a", "決定的に重要な", "important"], ["curious", "a", "好奇心の強い"], ["deliberate", "a", "意図的な"], ["dependent", "a", "依存している"],
    ["desperate", "a", "必死の"], ["domestic", "a", "国内の"], ["efficient", "a", "効率的な", "efficient"], ["elderly", "a", "年配の"], ["enormous", "a", "莫大な", "huge"],
    ["essential", "a", "不可欠な", "important"], ["exhausted", "a", "疲れ切った"], ["extinct", "a", "絶滅した"], ["flexible", "a", "柔軟な"], ["fragile", "a", "壊れやすい", "weak"],
    ["frequent", "a", "頻繁な"], ["genuine", "a", "本物の", "sincere"], ["grateful", "a", "感謝している"], ["harmful", "a", "有害な"], ["hostile", "a", "敵意のある"],
    ["humble", "a", "謙虚な", "humble"], ["identical", "a", "まったく同じ"], ["immediate", "a", "即座の"], ["inevitable", "a", "避けられない"], ["innocent", "a", "無罪の"],
    ["intelligent", "a", "知的な"], ["intense", "a", "激しい", "intense"], ["legal", "a", "合法の"], ["logical", "a", "論理的な", "logic"], ["mature", "a", "成熟した"],
    ["moderate", "a", "適度な"], ["modest", "a", "控えめな", "humble"], ["mutual", "a", "相互の"], ["negative", "a", "否定的な"], ["neutral", "a", "中立の"],
    ["numerous", "a", "多数の"], ["objective", "a", "客観的な"], ["obscure", "a", "不明瞭な", "vague"], ["ordinary", "a", "普通の", "typical"], ["permanent", "a", "永久の"],
    ["precise", "a", "精密な", "exact"], ["previous", "a", "以前の"], ["primitive", "a", "原始的な"], ["productive", "a", "生産的な", "efficient"], ["profound", "a", "深遠な"],
    ["prominent", "a", "著名な"], ["rapid", "a", "急速な"], ["rational", "a", "合理的な", "logic"], ["reluctant", "a", "気が進まない"], ["remarkable", "a", "注目すべき"],
    ["remote", "a", "遠く離れた"], ["responsible", "a", "責任がある"], ["rural", "a", "田舎の"], ["urban", "a", "都会の"], ["severe", "a", "厳しい"],
    ["significant", "a", "重要な", "important"], ["sincere", "a", "誠実な", "sincere"], ["slight", "a", "わずかな"], ["sophisticated", "a", "洗練された"], ["spontaneous", "a", "自発的な"],
    ["stable", "a", "安定した"], ["subjective", "a", "主観的な"], ["sufficient", "a", "足りている", "enough"], ["superior", "a", "より優れた"], ["temporary", "a", "一時的な"],
    ["thorough", "a", "徹底的な"], ["typical", "a", "典型的な", "typical"], ["vague", "a", "漠然とした", "vague"], ["valid", "a", "有効な"], ["vast", "a", "広大な", "huge"],
    ["visible", "a", "目に見える"], ["vital", "a", "極めて重要な", "important"], ["vulnerable", "a", "傷つきやすい", "weak"], ["fierce", "a", "どう猛な", "intense"], ["generous", "a", "気前のよい"],
    // 副詞
    ["accordingly", "d", "それに応じて", "therefore"], ["approximately", "d", "およそ"], ["barely", "d", "かろうじて", "rarely"], ["consequently", "d", "その結果", "therefore"], ["deliberately", "d", "故意に"],
    ["eventually", "d", "最終的に", "finally"], ["frankly", "d", "率直に"], ["gradually", "d", "徐々に"], ["hardly", "d", "ほとんど〜ない", "rarely"], ["immediately", "d", "ただちに"],
    ["merely", "d", "単に"], ["moreover", "d", "さらに"], ["nevertheless", "d", "それにもかかわらず"], ["occasionally", "d", "時折"], ["otherwise", "d", "さもなければ"],
    ["primarily", "d", "主として"], ["rarely", "d", "めったに〜ない", "rarely"], ["relatively", "d", "比較的"], ["simultaneously", "d", "同時に"], ["thoroughly", "d", "徹底的に"],
    ["ultimately", "d", "結局のところ", "finally"], ["virtually", "d", "事実上"], ["precisely", "d", "まさに"], ["accidentally", "d", "偶然に"], ["somewhat", "d", "いくぶん"],
  ],
  // toeic: TOEIC® L&R 対策（UI-98）。会議・出張・採用・経理・物流・店舗・不動産 など ビジネスの 場面で よく 出る 語を この ゲームの ために えらんだ もの
  // （公式の 語彙表や 問題集の 写しでは ない）。中学・高校の リストと おなじ 語は 入れない（tools/check-english.mjs）。
  toeic: [
    // 名詞
    ["invoice", "n", "請求書"], ["receipt", "n", "領収書"], ["quotation", "n", "見積書"], ["itinerary", "n", "旅程表"], ["agenda", "n", "議題"],
    ["minutes", "n", "議事録"], ["refund", "n", "返金"], ["inventory", "n", "在庫"], ["warehouse", "n", "倉庫"], ["shipment", "n", "出荷"],
    ["procurement", "n", "調達"], ["supplier", "n", "供給業者"], ["vendor", "n", "販売業者", "seller"], ["retailer", "n", "小売業者", "seller"], ["wholesaler", "n", "卸売業者"],
    ["distributor", "n", "販売代理店"], ["client", "n", "顧客", "customer"], ["patron", "n", "常連客", "customer"], ["subsidiary", "n", "子会社"], ["headquarters", "n", "本社"],
    ["branch", "n", "支店"], ["merger", "n", "合併"], ["acquisition", "n", "買収"], ["shareholder", "n", "株主"], ["revenue", "n", "収益"],
    ["expenditure", "n", "支出"], ["budget", "n", "予算"], ["quarter", "n", "四半期"], ["dividend", "n", "配当金"], ["asset", "n", "資産"],
    ["liability", "n", "負債"], ["audit", "n", "監査"], ["tax", "n", "税金"], ["payroll", "n", "給与名簿"], ["wage", "n", "賃金", "pay"],
    ["salary", "n", "給料", "pay"], ["bonus", "n", "賞与"], ["pension", "n", "年金"], ["applicant", "n", "応募者", "apply"], ["candidate", "n", "候補者", "apply"],
    ["reference", "n", "推薦状"], ["vacancy", "n", "欠員"], ["personnel", "n", "人事"], ["recruitment", "n", "採用"], ["orientation", "n", "新人研修", "training"],
    ["workshop", "n", "研修会", "training"], ["seminar", "n", "講習会", "training"], ["conference", "n", "会議", "meeting"], ["convention", "n", "大会", "meeting"], ["venue", "n", "会場"],
    ["attendee", "n", "出席者"], ["participant", "n", "参加者"], ["registration", "n", "登録"], ["admission", "n", "入場料"], ["reservation", "n", "予約"],
    ["accommodation", "n", "宿泊施設"], ["fare", "n", "運賃"], ["toll", "n", "通行料"], ["luggage", "n", "手荷物"], ["layover", "n", "乗り継ぎ"],
    ["arrival", "n", "到着"], ["maintenance", "n", "保守"], ["repair", "n", "修理"], ["warranty", "n", "保証書"], ["defect", "n", "欠陥"],
    ["complaint", "n", "苦情"], ["feedback", "n", "感想"], ["questionnaire", "n", "質問票"], ["proposal", "n", "提案書"], ["contract", "n", "契約", "deal"],
    ["agreement", "n", "合意", "deal"], ["clause", "n", "条項"], ["extension", "n", "内線"], ["memo", "n", "社内回覧"], ["bulletin", "n", "会報"],
    ["announcement", "n", "発表"], ["press", "n", "報道機関"], ["publicity", "n", "広報", "ad"], ["advertisement", "n", "広告", "ad"], ["brochure", "n", "パンフレット"],
    ["catalog", "n", "商品目録"], ["sample", "n", "見本"], ["prototype", "n", "試作品"], ["specification", "n", "仕様"], ["component", "n", "部品"],
    ["stationery", "n", "文房具"], ["appliance", "n", "家電製品"], ["merchandise", "n", "商品"], ["competitor", "n", "競合他社"], ["demand", "n", "需要"],
    ["growth", "n", "成長"], ["forecast", "n", "予測"], ["strategy", "n", "戦略"], ["target", "n", "目標"], ["initiative", "n", "取り組み"],
    ["outcome", "n", "成果"], ["productivity", "n", "生産性"], ["efficiency", "n", "効率"], ["expertise", "n", "専門知識"], ["credential", "n", "資格", "cert"],
    ["certificate", "n", "証明書", "cert"], ["license", "n", "免許"], ["permit", "n", "許可証"], ["compliance", "n", "法令順守"], ["inspection", "n", "検査"],
    ["assessment", "n", "査定"], ["promotion", "n", "昇進"], ["transfer", "n", "異動"], ["retirement", "n", "退職"], ["colleague", "n", "同僚"],
    ["supervisor", "n", "上司"], ["executive", "n", "重役"], ["representative", "n", "担当者"], ["receptionist", "n", "受付係"], ["accountant", "n", "会計士"],
    ["architect", "n", "建築家"], ["technician", "n", "技術者"], ["contractor", "n", "請負業者"], ["intern", "n", "研修生"], ["tenant", "n", "入居者"],
    ["landlord", "n", "家主"], ["property", "n", "不動産"], ["premises", "n", "敷地"], ["cafeteria", "n", "社員食堂"], ["directory", "n", "名簿"],
    ["lounge", "n", "談話室"], ["pharmacy", "n", "薬局"], ["grocery", "n", "食料品店"], ["cuisine", "n", "料理"], ["catering", "n", "仕出し"],
    ["beverage", "n", "飲み物"], ["refreshment", "n", "軽食"], ["donation", "n", "寄付"], ["fundraiser", "n", "募金活動"],
    // 動詞
    ["reimburse", "v", "払い戻す"], ["renovate", "v", "改装する"], ["relocate", "v", "移転する"], ["postpone", "v", "延期する"], ["reschedule", "v", "予定を変更する"],
    ["cancel", "v", "取り消す"], ["submit", "v", "提出する"], ["revise", "v", "改訂する"], ["implement", "v", "実施する"], ["negotiate", "v", "交渉する"],
    ["allocate", "v", "配分する", "allot"], ["assign", "v", "割り当てる", "allot"], ["delegate", "v", "任せる"], ["oversee", "v", "監督する"], ["inspect", "v", "点検する"],
    ["verify", "v", "検証する"], ["retrieve", "v", "回収する"], ["dispatch", "v", "発送する", "send"], ["ship", "v", "出荷する", "send"], ["purchase", "v", "購入する"],
    ["lease", "v", "賃貸する"], ["invest", "v", "投資する"], ["merge", "v", "合併する"], ["launch", "v", "発売する"], ["advertise", "v", "宣伝する"],
    ["endorse", "v", "支持する"], ["sponsor", "v", "後援する"], ["host", "v", "主催する"], ["attend", "v", "出席する"], ["register", "v", "登録する"],
    ["enroll", "v", "入会する"], ["subscribe", "v", "定期購読する"], ["renew", "v", "更新する"], ["expire", "v", "期限が切れる"], ["accommodate", "v", "収容する"],
    ["reserve", "v", "予約する"], ["notify", "v", "通知する"], ["remind", "v", "思い出させる"], ["update", "v", "最新にする"], ["install", "v", "設置する"],
    ["assemble", "v", "組み立てる"], ["manufacture", "v", "製造する"], ["distribute", "v", "配布する"], ["circulate", "v", "回覧する"], ["compile", "v", "編集する"],
    ["draft", "v", "下書きする"], ["proofread", "v", "校正する"], ["forward", "v", "転送する"], ["enclose", "v", "同封する"], ["specify", "v", "明記する"],
    ["outline", "v", "概説する"], ["summarize", "v", "要約する"], ["clarify", "v", "明確にする"], ["address", "v", "取り組む"], ["resolve", "v", "解決する"],
    ["streamline", "v", "効率化する"], ["boost", "v", "高める"], ["exceed", "v", "上回る", "beat"], ["surpass", "v", "しのぐ", "beat"], ["fluctuate", "v", "変動する"],
    ["hire", "v", "雇う"], ["recruit", "v", "募集する"], ["dismiss", "v", "解雇する"], ["resign", "v", "辞職する"], ["retire", "v", "引退する"],
    ["commute", "v", "通勤する"], ["greet", "v", "出迎える"], ["waive", "v", "免除する"], ["charge", "v", "請求する"], ["owe", "v", "借金がある"],
    ["finalize", "v", "仕上げる"], ["coordinate", "v", "調整する"], ["facilitate", "v", "円滑にする"], ["collaborate", "v", "協力する"], ["consult", "v", "相談する"],
    ["inquire", "v", "問い合わせる"], ["assess", "v", "評価する"], ["comply", "v", "従う"], ["prioritize", "v", "優先する"], ["anticipate", "v", "予想する"],
    ["vacate", "v", "立ち退く"], ["accelerate", "v", "加速する"], ["undergo", "v", "受ける"], ["excel", "v", "秀でる"], ["thrive", "v", "繁盛する"],
    // 形容詞
    ["annual", "a", "年に一度の"], ["quarterly", "a", "四半期の"], ["confidential", "a", "機密の"], ["complimentary", "a", "無料の"], ["mandatory", "a", "義務的な"],
    ["optional", "a", "任意の"], ["eligible", "a", "資格のある", "able"], ["qualified", "a", "適任の", "able"], ["affordable", "a", "手ごろな"], ["reliable", "a", "信頼できる"],
    ["durable", "a", "耐久性のある"], ["defective", "a", "欠陥のある"], ["punctual", "a", "時間を守る"], ["preliminary", "a", "予備の", "temp"], ["tentative", "a", "仮の", "temp"],
    ["interim", "a", "暫定の", "temp"], ["upcoming", "a", "近く行われる"], ["outstanding", "a", "傑出した", "famous"], ["renowned", "a", "名高い", "famous"], ["overdue", "a", "期限切れの"],
    ["vacant", "a", "空いている"], ["spacious", "a", "広々とした"], ["lucrative", "a", "もうかる"], ["competitive", "a", "競争力のある"], ["comprehensive", "a", "包括的な", "wide"],
    ["extensive", "a", "広範囲の", "wide"], ["substantial", "a", "相当な", "enough"], ["ample", "a", "十分な", "enough"], ["consecutive", "a", "連続した"], ["adjacent", "a", "隣接した"],
    ["prospective", "a", "見込みのある"], ["promotional", "a", "販売促進の"], ["financial", "a", "財務の"], ["corporate", "a", "企業の"], ["administrative", "a", "管理上の"],
    ["technical", "a", "技術的な"], ["versatile", "a", "用途の広い"], ["courteous", "a", "礼儀正しい", "polite"], ["attentive", "a", "気配りのある", "polite"], ["knowledgeable", "a", "知識豊富な", "skill"],
    ["experienced", "a", "経験豊富な", "skill"], ["innovative", "a", "革新的な"], ["sustainable", "a", "持続可能な"], ["hazardous", "a", "危険な"], ["refundable", "a", "返金可能な"],
    ["accessible", "a", "利用しやすい", "easy"], ["convenient", "a", "都合のよい", "easy"], ["pending", "a", "保留中の"], ["exclusive", "a", "独占的な"], ["scenic", "a", "景色のよい"],
    ["tight", "a", "余裕のない"], ["reasonable", "a", "妥当な"],
    // 副詞
    ["promptly", "d", "迅速に"], ["temporarily", "d", "一時的に"], ["tentatively", "d", "仮に"], ["subsequently", "d", "その後に"], ["previously", "d", "以前に"],
    ["currently", "d", "現在は"], ["shortly", "d", "まもなく"], ["punctually", "d", "時間どおりに"], ["significantly", "d", "大幅に", "much"], ["considerably", "d", "かなり", "much"],
    ["steadily", "d", "着実に"], ["exclusively", "d", "独占的に"], ["mutually", "d", "互いに", "together"], ["unanimously", "d", "満場一致で"], ["regularly", "d", "定期的に"],
    ["annually", "d", "毎年"], ["separately", "d", "別々に"], ["jointly", "d", "共同で", "together"], ["directly", "d", "直接に"], ["remotely", "d", "遠隔で"],
    ["efficiently", "d", "効率よく"], ["strictly", "d", "厳しく"], ["originally", "d", "もともと"], ["increasingly", "d", "ますます"], ["roughly", "d", "おおよそ"],
    ["apparently", "d", "どうやら"], ["consistently", "d", "一貫して"], ["sufficiently", "d", "十分に"], ["conveniently", "d", "便利に"], ["overseas", "d", "海外で"],
  ],
};
